---
- name: Build/rebuild eXist 5.x
  become_user: "{{ exist_instuser }}"
  # java.io.tmpdir needed to work around an atomic move across filesystems
  # skipTest because some test fail and we're not doing dev here
  # target mac-dmg-on-unix will fail on Amazon Linux AWS1
  shell: "MAVEN_OPTS='-Djava.io.tmpdir={{ exist_home }}/tmp' /usr/local/bin/mvn clean package -D skipTests -P '!mac-dmg-on-unix' >build.log 2>&1"
  args:
    chdir: "{{ exist_srcpath }}"
  tags:
    - install
    - src-install
    - exist5

- name: Locate compiled eXist archive
  find:
    paths: "{{ exist_srcpath }}/exist-distribution/target"
    patterns: "exist-distribution*unix.tar.bz2"
  register: compiled_archive
  tags:
    - install
    - src-install
    - exist5

- name: Copy compiled eXist archive to archive directory on the local Ansible host
  copy:
    src: "{{ item }}"
    dest: "{{ exist_home }}/tmp/"
    owner: "{{ exist_instuser }}"
    group: "{{ exist_group }}"
  with_items: compiled_archive.files
  #with_fileglob:
  #  - "{{ exist_srcpath }}/exist-distribution/target/exist-distribution*unix.tar.bz2"
  #delegate_to: 127.0.0.1
  tags:
    - install
    - src-install
    - exist5

- name: Install exist archive
  unarchive:
    src: "{{ item }}"
    dest: "{{ exist_home }}"
    remote_src: yes
    owner: "{{ exist_instuser }}"
    group: "{{ exist_group }}"
    #creates: "{{ exist_path }}/VERSION.txt"   # 4.x
    #creates: "{{ exist_path }}/etc/conf.xml"  # 5.x
    extra_opts: [ '--transform=s:^[^/]\+:{{ exist_instname }}:;' ]
  with_items: compiled_archive.files
  #with_fileglob:
  #  - "{{ exist_srcpath }}/exist-distribution/target/exist-distribution*unix.tar.bz2"
  when: not exist_is_installed or exist_replace_installation
  tags:
    - install
    - src-install
    - exist5
