---
- name: Set facts for this exist instance
  set_fact:
    exist_path: "{{ exist_home }}/{{ exist_instname }}"

- name: Debug0
  debug:
    msg: 'exist_path: {{ exist_path }} exist_instname: {{ exist_instname }} exist_instuser: {{ exist_instuser }}'

- name: Include user setup tasks
  include_tasks: setup-user.yml

- name: Include pre-installation tasks
  include_tasks: preinstall.yml

- name: Set defaults if no facts are known a about this eXist instance
  set_fact:
    exist_is_installed: false
    exist_is_running: false
    exist_current_gitsrc: false
    exist_current_revision: ""
  when: exist_instname not in ansible_local

- name: Set facts for this eXist instance
  set_fact:
    exist_is_installed: "{{ ansible_local[exist_instname]['exist_installed'] }}"
    exist_is_running: "{{ ansible_local[exist_instname]['exist_running'] }}"
    exist_current_gitsrc: "{{ ansible_local[exist_instname]['exist_gitsrc'] }}"
    exist_current_revision: "{{ ansible_local[exist_instname]['exist_revision'] }}"
  when: exist_instname in ansible_local

- name: Include tasks to install exist from source
  include_tasks: install-from-source.yml
  when: exist_install_method == "source"

- name: Include tasks to install exist from pre-packaged archive file
  include_tasks: install-archive.yml
  when: exist_install_method == "remote_archive" or exist_install_method == "local_archive"

- name: Include custom xar installation tasks (eXist 4.x)
  include_tasks: custom-xar-install.yml
  when: exist_install_custom_xars and exist_major_version == 4

- name: Include custom xar installation tasks (eXist 5.x)
  fail:
    msg: 'Custom Xar installation currently not supported on 5.x'
  when: exist_install_custom_xars and exist_major_version == 5

- name: Include post-installation pre-startup tasks
  include_tasks: postinstall.yml

- name: Include startup exist and post-startup tasks
  include_tasks: startup.yml
